# Generated by Django 3.2.9 on 2021-12-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('name', models.CharField(default='', max_length=20)),
                ('sale_name', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('hide_status', models.BooleanField(default=0)),
                ('sold_out_status', models.BooleanField(default=0)),
            ],
        ),
    ]
