# Generated by Django 3.2.9 on 2021-12-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='products_product_opt',
        ),
    ]
