# Generated by Django 3.2.9 on 2021-12-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPage', '0003_rename_products_products_product_opt'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginId', models.CharField(default='', max_length=20)),
                ('loginPw', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='markets_market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='hide_status',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='sale_name',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='sold_out_status',
        ),
        migrations.RemoveField(
            model_name='products_product_opt',
            name='update_date',
        ),
        migrations.AddField(
            model_name='products_product_opt',
            name='color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='products_product_opt',
            name='size',
            field=models.CharField(default='s', max_length=20),
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField()),
                ('update_date', models.DateTimeField()),
                ('sale_name', models.CharField(default='', max_length=20)),
                ('sale_price', models.IntegerField(default=0)),
                ('hide_status', models.BooleanField(default=0)),
                ('sold_out_status', models.BooleanField(default=0)),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPage.markets_market')),
            ],
        ),
        migrations.AlterField(
            model_name='products_product_opt',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPage.markets_market'),
        ),
    ]
